### ISSUE TITLE
Ovary anatomogram

### ISSUE THREAD

**Issue by lingyun1010** [ebi-gene-expression-group/organ-anatomogram#43]
More organs and species will be added into the organ-anatomogram component. The logic is the same as the other organs. New svgs are shared in Google Drive.

Tarry as the illustrator and Damien is the curator.

**Comment by lingyun1010** [comment]
We had a meeting before Christmas 2023 with Tarryn and Damien, another meeting is scheduled with Silvie on 25th Jan 2024. This would be a more social and summary meeting to introduce each other and hand over thingie formally. Regarding the anatomogram svg, please find the latest version in google drive https://drive.google.com/drive/folders/0AFsA7lQKkNVFUk9PVA.

**Comment by lingyun1010** [comment]
We had a meeting on 2nd Feb with Tarryn, Damien and Upendra. The ovary main svg should be fixed for the blue box. Github repository has been shared to the team. My local commits had been pushed to the branch.

**Comment by upendrakumbham** [comment]
After the above meeting, Damien mentioned that he tested the live anatomograms of the fly ovary and testis and found several issues with some cell labels. We will discuss all the issues in today's (9th of Feb) meeting.

- He shared the issues list in the email:
```
Ovary anatomograms:

* FBbt:00004903 (“follicle stem cell”)
  On the ovariole-level anatomogram, this labels what should be follicle cells (FBbt:00004904) instead.

* FBbt:00004924 (“uterus”)
  The shape seems hidden beneath another one, only a small fragment is highlighted.

Testis anatomograms:

* FBbt:00049329 (“adult lateral horn AD3b1 neuron”)
  This is an incorrect ID (it refers to a brain cell that has nothing to do in the testis), it should be FBbt:0004929 (“male germline stem cell”) instead.

* FBbt:0004927 FBbt:0004928 FBbt:0004930 FBbt:0004933 FBbt:0004959
  All those IDs are missing one leading zero (it should be FBbt:00004927, FBbt:00004938, etc.).

* FBbt:00004931
  That shape should be labeled as FBbt:00004935.

* FBbt:00004942 FBbt:00005287 FBbt:00007138
  The labels are correct but the coloring of the shapes seems weird or incomplete.

I am happy to discuss those issues in our meeting on Friday.
```

**Comment by upendrakumbham** [comment]
We had a meeting today,  we discussed all the above issues and Tarry shared the latest `overy.ovary avg` file to fix a bug.
During our meeting, I replaced the code with the latest SVG file and tested it. Tarry and Damien are happy with the latest SVG file fix.

- Actions for the next meeting:
Tarry mentioned that she is going to fix all the discussed issues and share the latest files by Monday. I will test those SVG files in my local application and be ready to show them. we will discuss those changes in the next meeting.

**Comment by upendrakumbham** [comment]
We(Lingyun and I) had a meeting with Tarryn and Damien, today.  We had a final testing with them all our SVGs in the Anatomogram application. All good as per them. one of the link SVG germarium behaved a bit weird in the Chrome browser and it looks alright in the Firefox for me and Lingyun. But this doedn't looks like a show stopper to integrate these SVGs into our application as part of coming release.

Thank you @lingyun1010 for fixing a major bug to progress further on this task , it is a layer issue. Tarryn coudn't fix it ,though.

I comitted all the code changes into the  Anatomogram repository. Lingyun reviewed PR as well.
